config.code = 01111
config.message = These are recently edited files. Do not suggest code that has been deleted.
config.list = python,java,c,php,kotlin,javascript
config.valuesMap = {name: 'Neider Vélez', email: 'neider@ejemplo.com'}